### ISSUE TITLE
Version 1.50 - InvalidEnumMemberPath - /MultiValue

### ISSUE THREAD

**Issue by jongooding19** [SAP-samples/data-warehouse-cloud-connectors#10]
There is 2 connections in this version. 
The Catalog connection works 
The data connection gives the error:
Details: "OData: The feed's metadata document appears to be invalid. Error: The metadata document could not be read from the message content.
InvalidEnumMemberPath : 'Collection(Capabilities.FilterExpressionRestrictionType)/MultiValue' is not a valid enum member path. : (96, 14)
"

**Comment by OlafFischer** [comment]
Hi Jared,
 
The odata response of datasphere contains mainly two parts: the real data and the metadata describing the real data.
 
For sure, PowerBi reads the metadata part and parses it to understand data types etc. Now it seems that the metadata provided by datasphere seems to be incorrect from PowerBi perspective. Now the question is: who is right? A typical one if you write connectors between two products 😊.
 
What I would recommend narrowing down the root cause:
 
**Getting the facts:**
 
Capture the Request and Response. This could be done using fiddler or another http sniffer or as an alternative, build the URL for your service request manually and let the browser call the API.

In the beginning of the response, you see a URL pointing to the metadata. Open and download it. In fiddler you see the request for metadata already and you can pick it from there.
 
**Narrow down the root cause:**
- The parameter belongs to a certain column of your datasphere view. When you have identified it, remove it from the source and check if it fixes the topic.
- If yes, check the data type – is it different to the others?

Best regards, Olaf

**Comment by andrewzdyer** [comment]
Hi Olaf
I'm having the same problem. I can't install fiddler on my corporate PC, so I used Postman to get the metadata o the service. 
The annotation causing the error seems to be at the entity set not at the attribute level. The annotation looks like:

<Annotations Target="StandaloneService.EntityContainer/DV_Purchasing_Materials">
                <Annotation Term="Capabilities.FilterRestrictions">
                    <Record Type="Capabilities.FilterRestrictionsType">
                        <PropertyValue Property="FilterExpressionRestrictions" EnumMember="Collection(Capabilities.FilterExpressionRestrictionType)/MultiValue"/>

I can't see anything in Datasphere that might control this.

Any thoughts!

**Comment by OlafFischer** [comment]
Hi Andrewzdyer,

please check out the latest comment on issue #12 - in addition, could you please share the annotation sample you found? In your last reply, you write "The annonation looks like:" - but unfortunately not followed by a sample.

Thanks, Olaf

**Comment by andrewzdyer** [comment]
Thanks Olaf. I forgot to add the annotation text as code. I have edited the last comment to fix this :)

Based on your comment in issue 12, I'll have a look at the view settings in Datasphere to see where a filter may be set. It doesn't appear to be on a field, rather on the entity. If I find config to update in Datasphere to update I will post.
