### ISSUE TITLE
Error during login step to datasphere from Power BI

### ISSUE THREAD

**Issue by Guru263** [SAP-samples/data-warehouse-cloud-connectors#11]
I have added custom connector as detailed in the steps and tried to connect datasphere from Power BI.
After Get Data-> SAP Datasphere - Data(1.50) (Beta), I key in credentials and get message " uh oh Something went amiss". Detailed steps and screenshots added in word document. 

Please let me know if I had missed something.

[Custom Connector for PBI.docx](https://github.com/SAP-samples/data-warehouse-cloud-connectors/files/12037714/Custom.Connector.for.PBI.docx)

Thanks
Guru

**Comment by Guru263** [comment]
update

I turned a setting in Power BI - Files - options - Global/security - Authentication from browser
![image](https://github.com/SAP-samples/data-warehouse-cloud-connectors/assets/139448594/7e78b339-f66a-4ada-9ea3-8511d040ef44)
 
And after which when I re-try to connect getting a different msg now.

![image](https://github.com/SAP-samples/data-warehouse-cloud-connectors/assets/139448594/42a97858-fca2-42ed-8749-a64b6f04325e)

**Comment by Guru263** [comment]
Hi Olaf, can you please help on this matter.

**Comment by OlafFischer** [comment]
Hi Guru263,
it seems that using your default web browser improved the situation. The following error message indicates, that the connection can't determine the URL to call.

One potential root cause could be an unexpected configuration file. Before you can use the connector, you need adjust the file connections.json - could you please verify the content? Note that the content changed from previous versions, e.g. you need to specify a host name and not the full URL any more.

Best regards, Olaf

**Comment by Guru263** [comment]
Thanks Olaf.
I think I have followed as mentioned in the steps. Only given host name and not URL. Still it not works.

**Comment by OlafFischer** [comment]
Could you please re-try with the latest version? I did a correction dealing with a similar error message.
If  the issue still persists, please re-open the conversation.
Best regards, Olaf
