### ISSUE TITLE
DataFormat.Error: [DataFormat.Error] We found an unexpected character in the JSON input.

### ISSUE THREAD

**Issue by Sidraz99** [SAP-samples/data-warehouse-cloud-connectors#26]
I am getting the data format error when I try to load analytical/ relation view . It seems like its generating a wrong JSON as I can see in details the format which is getting generated indicates that view name is getting added twice. 

![image](https://github.com/user-attachments/assets/63f9aebf-9cf4-4489-86c5-5ba30aa5d462)

**Comment by gustavokath** [comment]
Hi @Sidraz99,

The URL looks correct from the OData point of view. This error means the response is not a valid JSON, there could be several root causes for that. It could be due to authentication issues or wrong query parameters.

I've tried to find you request on the application logs for better support, but I was not able to. If you need further support, please open a SAP Customer Indent so you can share more details.

Thanks

**Comment by Sidraz99** [comment]
Thank you @gustavokath We will raise the customer incident.

**Comment by Sidraz99** [comment]
The issue was resolved after using  api/v1/dwc/consumption/relational/Space Name/ViewName intead of V4.  We can close this issue. However I would like to know if Hierarchies are supported in the current release?

**Comment by Sidraz99** [comment]
The issue is resolved now.
